name: Time Enthusiast
favicon: null
layout_spectrum: 0.8087267903611064
typography_spectrum: 0.7535314285196364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3838009489700198
  lightness: 0.18764938204549253
  saturation: 0.8039293915499002
  rhythmicContrast: 0.1658020259346813
purpose: []
